# Centralising SSH public key configuration
# Avoids the live-boot requirement to generate /home/$LIVE_USER/.ssh/authorized_keys
# Instead we can bake in per-user 'authorized_keys' files
AuthorizedKeysFile /etc/ssh/authorized_keys/%u
