ARG DEBIAN_OCI_TAG

# https://hub.docker.com/_/debian/tags
FROM debian:${DEBIAN_OCI_TAG}
ARG SNAPSHOT_TIMESTAMP

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
                    --update \
                    --snapshot ${SNAPSHOT_TIMESTAMP} \
                    --no-install-recommends \
                    # 'ca-certificates' not installed by default, ignore invalid cert
                    --option 'Acquire::https::snapshot.debian.org::Verify-Peer=false' \
                    --option 'Acquire::Check-Valid-Until=false' \
                    live-build ca-certificates && \
    rm --recursive \
       --force \
       /var/lib/apt/lists/*
