#!/usr/bin/env bash
set -u

lb config noauto \
	  --apt-options '--yes --option Acquire::Retries=5 --option Acquire::Check-Valid-Until=false' \
	  --apt-source-archives false \
	  --bootappend-live 'boot=live live-config.components ip=frommedia' \
	  --clean \
