#!/usr/bin/env bash
set -u

lb config noauto \
	  --apt-options '--yes --option Acquire::Retries=5 --option Acquire::Check-Valid-Until=false' \
	  --apt-source-archives false \
	  --bootappend-live 'boot=live live-config.components ip=frommedia console=tty1 console=uart8250,io,0x3060,115200' \
	  --clean \
	  --debian-installer none \
	  --debootstrap-options='--include=ca-certificates' \
	  --distribution ${MAYFLIES_LB_DEBIAN_RELEASE} \
	  --ignore-system-defaults \
	  --mirror-binary ${MAYFLIES_LB_MIRROR} \
	  --mirror-bootstrap ${MAYFLIES_LB_MIRROR} \
	  --mirror-chroot ${MAYFLIES_LB_MIRROR} \
	  --mirror-debian-installer ${MAYFLIES_LB_MIRROR} \
	  --parent-mirror-binary ${MAYFLIES_LB_MIRROR} \
	  --parent-mirror-bootstrap ${MAYFLIES_LB_MIRROR} \
	  --parent-mirror-chroot ${MAYFLIES_LB_MIRROR} \
	  --parent-mirror-debian-installer ${MAYFLIES_LB_MIRROR} \
	  --memtest 'memtest86+' \
	  --mode debian \
	  --net-tarball false \
	  --updates false \
	  --security false \
	  --image-name "blu-$(basename "${PWD}")-$(date +"%Y:%m:%d-%H:%M:%S")" \
	  --verbose \
	  --zsync false

# System-wide configuration
cp --verbose \
   --recursive \
   --force \
   auto/config.d/* config/

# 'live-build' prepackaged reproducible build scripts
cp --verbose \
   --symbolic-link \
   --force \
   /usr/share/doc/live-build/examples/hooks/reproducible/* config/hooks/normal/

# Build-time live-build(7) environment variables
env | grep ^LB_ | tee --append config/includes.chroot/etc/default/mayflies/live-build.env

# Build-time Mayflies "project" specific environment variables
env | grep ^MAYFLIES_ | tee --append config/includes.chroot/etc/default/mayflies/project.env
echo "MAYFLIES_LB_VERSION=$(lb --version)" | tee --append config/includes.chroot/etc/mayflies/project.env

# Source generated LB configuration as environment variables
set -a
for conf in config/{binary,bootstrap,chroot,common,source}; do source "${conf}"; done
set +a

# Render templates (.envsubst extension) & cleanup
for template in $(find config/ -name '*.envsubst'); do
  envsubst < "${template}" > "${template%.*}"
  rm "${template}"
done

# Global, miscellaneous environment variables (catch-all)
env | grep --invert-match --extended-regexp '(^LB_|^MAYFLIES_)' | tee --append config/includes.chroot/etc/default/mayflies/global.env
